# Generated by Django 3.0.5 on 2024-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0019_auto_20240418_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEncryptedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_field', models.CharField(max_length=255)),
            ],
        ),
    ]
